export const ADD_CONVERSATION = "ADD_CONVERSATION";
export const ADD_CONVERSATIONS = "ADD_CONVERSATIONS";
export const CLEAR_CONVERSATION = "CLEAR_CONVERSATION";
export const SORT_CONVERSATIONS = "SORT_CONVERSATIONS";
export const SET_CONVERSATIONS = "SET_CONVERSATIONS";

export const REMOVE_CONVERSATION = "REMOVE_CONVERSATION";
